name: Deploy CRM Stack

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  FRONTEND_IMAGE_NAME: mugunth140/crm-frontend
  BACKEND_IMAGE_NAME: mugunth140/crm-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./crm-frontend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:latest

      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./crm-backend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Trigger VPS Webhook
        run: |
          curl -X POST "http://${{ secrets.VPS_IP }}:9000/hooks/deploy-majestan" \
               -H "X-Deploy-Token: ${{ secrets.WEBHOOK_SECRET }}"
